config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "pages#root"
  get "players/login", to: "players#login_page"
  post "players/login", to: "players#login"

  mount ActionCable.server => "/cable"

  get "secret/admin_page", to: "players#index"
  resources :games, only: [:create, :show, :update]
  resources :players, only: [:create, :show, :update, :edit]
  resources :conversations, only: [:create, :show]
  resources :messages, only: [:create]
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :player

  validate :check_player
  after_validation :mark_number
  before_save :broadcast
  # before_save :mark_phone
  after_create :mark_unread

  attr_accessor :no_links

  def extra_info
    JSON.parse(self.extra)
  end

  private
    def check_player
      if self.player.left?
        errors.add(:player, "must still be connected")
      end
    end

    def mark_number
      unless no_links
        # Scanning for 5 digit long numbers
        numbers = self.contents.scan(/\d{5}/)
        links = numbers.uniq.map do |number|
          target = Player.find_by(number: number, game: self.player.game)
          if target
            { number: number, id: target.id }
          else
            nil
          end
        end
        links.compact!

        if links.length > 0
          self.extra = JSON.parse(extra).merge(links: links.find_all { |n| n }).to_json
        end
      end
    end

    # def mark_phone
    #   numbers = self.contents.scan(/(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/)

    #   match = "333-333-3333 blah".match(/^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*$/)

    #   if numbers.length > 0
    #     self.extra = JSON.parse(extra).merge(phone: numbers.uniq.to_json)
    #   end
    # end

    def mark_unread
      self.conversation.notifications.where.not(player: self.player).update(seen: false)
    end

    def broadcast
      broadcast = { message: self.contents, number: self.player.number, player: self.player.id, extra: self.extra, conversation: self.conversation.id, order_num: self.order_num, type: "msg" }

      players = self.conversation.players
      players.each do |player|
        broadcast[:tab] = players.where.not(id: player.id).pluck(:number).join(", ")
        player.broadcast_to(broadcast)
      end
      # ActionCable.server.broadcast("chat_Conversation_#{self.conversation.id}", message: self.contents, number: self.player.number, extra: self.extra)
    end
end

app/views/messages/_show.html.erb
<% if message.extra_info["system_message"] %>
  <div class ="message system" data-order="<%=message.order_num%>">
    <%= message.contents %>
  </div>
<% else %>
  <div class="<%= message.player == current_player ? "from" : "to" %> message" data-order="<%=message.order_num%>">
    <div class="chat-info">
      <span class="chat-player-number"><%= message.player.number %></span>
      <span class="time-ago">(<%= time_ago_in_words(message.created_at) %> ago)</span>
    </div>
    <div class="message-contents">
      <%
        # This is very bad formatting, but I can't figure out how to get this properly built
        # I need both the html generation methods
        contents = sanitize(message.contents)
        if message.extra_info.has_key?("links")
          message.extra_info["links"].each do |link|
            contents.gsub!(
              link["number"], 
              link_to(link["number"], conversations_path(players: [link["id"], current_player.id]), method: :post)
            )
          end
        end
        if message.extra_info.has_key?("phone")
          message.extra_info["phone"].each do |phone|
            contents.gsub!(
              phone,
              link_to(phone, "tel:#{phone}")
            )
          end
        end
      %>
      <%= contents.html_safe %>
    </div>
  </div>
<% end %>