config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "pages#root"
  get "players/login", to: "players#login_page"
  post "players/login", to: "players#login"

  mount ActionCable.server => "/cable"

  get "secret/admin_page", to: "players#index"
  resources :games, only: [:create, :show, :update]
  resources :players, only: [:create, :show, :update, :edit]
  resources :conversations, only: [:create, :show]
  resources :messages, only: [:create]
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  belongs_to :game, optional: true

  enum role: [:participant, :host, :hrn]

  has_many :messages
  has_many :notifications
  has_many :conversations, through: :notifications

  attr_accessor :code

  validate :game_exists?, on: :create
  validate :valid_game?, on: :create
  before_create :set_game
  before_create :set_number
  after_create :broadcast_creation

  def broadcast_to(data)
    ActionCable.server.broadcast("game_channel_#{id}", data)
  end

  def channel
    ActionCable.server.remote_connections.where(current_player: self)
  end

  def find_conversation(player)
    convo = conversations
      .eager_load(:players)
      .find_by("players.id = ?", player.id)
    convo = Conversation.create(players: [self, player]) if convo.nil?
    convo
  end

  def any_unread?
    notifications.any? { |n| !n.seen? }
  end

  def leave
    conversations.each do |conversation|
      Message.create(
        contents: "- #{number} has disconnected -",
        conversation: conversation,
        player: self,
        extra: { system_message: true }.to_json,
        no_links: true,
        order_num: conversation.last_order_num + 1
      )
    end

    notifications.update_all(seen: true)

    if change.nil? && fate.nil?
      self.change = game.changes.sample
      self.fate = game.fates.sample
      self.save
    end

    ActionCable.server.broadcast(
      "host_channel_#{game.id}",
      type: "player_leave",
      id: id
    )
  end

  private

    def set_number
      return if number

      loop do
        self.number = Random.rand(100_000).to_s.rjust(5, "0")
        break unless Player.exists?(left: false, number: number)
      end
    end

    def set_game
      return unless game.nil? && !code.nil?

      self.game = Game.find_by(code: code)
    end

    def broadcast_creation
      return unless game

      ActionCable.server.broadcast(
        "host_channel_#{game.id}",
        type: "new_player",
        number: number,
        count: game.players.count,
        id: id
      )
    end

    def game_exists?
      return unless game.nil? && !code.nil? && !Game.exists?(code: code)

      errors.add(:game, "not found.")
    end

    def valid_game?
      return unless game

      if game.state != "before"
        errors.add(:game, "has already started")
      elsif game.players.count >= 5
        errors.add(:game, "is full")
      end
    end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :redirect_to_main, only: [:login_page]
  before_action :check_player, only: [:show, :edit, :update]
  before_action :match_player, only: [:show, :edit, :update]

  def create
    @player = Player.new(code: params[:player][:code].upcase)
    if @player.save
      set_cookies(@player)
      redirect_to @player
    else
      flash[:alert] = @player.errors.full_messages[0]
      redirect_to root_path
    end
  end

  def show
    @player = Player.includes(:game, :conversations).find(params[:id])
    unless @player.participant?
      redirect_to current_player.game
    end
  end

  def edit
    @player = Player.find(params[:id])
    @outcomes = @player.game.outcomes("#{@player.cache_key}/outcomes")
  end

  def update
    player = Player.find(params[:id])
    if player_params[:left] && (player_params[:left] == "true" || player_params[:left] == true)
      player.leave
    end
    player.update(player_params)
    redirect_to player
  end

  def login_page
    @games = Game.includes(:players).where.not(state: "end").order(created_at: :desc)
  end

  def index
    @games = Game.all.order(created_at: :desc)
  end

  def login
    player = Player.find_by(id: params[:id])
    if player
      set_cookies(player)
      redirect_to player
    else
      flash[:alert] = "We could not find that player"
      redirect_to root_path
    end
  end

  private
    def player_params
      params.require(:player).permit(:left, :change, :fate)
    end

    # games last 90 minutes + an extra 90 minutes for before game events. Just to be safe
    def set_cookies(player)
      cookies[:current_player] = { value: player.id, expires: 3.hours }
      cookies[:current_game] = { value: player.game.id, expires: 3.hours }
    end
end

app/views/players/_conversation_list.html.erb
<div id="conversations-<%= player.id %>" class="conversations">
  <% conversations.order(:created_at).each do |conversation| %>
    <%= link_to conversation_path(conversation, params: use_from ? {from: player} : {}) do %>
      <%= content_tag(:div, id: "conversation-#{conversation.id}", class: "conversation #{"unseen" unless conversation.read(player)}") do %>
        <%= (conversation.players.pluck(:number) - [player.number]).join(",") %> 
        <% if conversation.messages.any? %>
          (<span class="conversation-preview"><%= truncate(conversation.messages.order(:order_num).last.contents, length: 50) %></span>)
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/players/edit.html.erb
<div id="player-banner">
  <div id="left">
    <div>
      <%= link_to @player.host? ? game_path(@player.game) : player_path(@player) do %>
        <%= image_tag "back.png", id: "nav", class: @player.any_unread? ? "notification" : "" %>
      <% end %>
    </div>
    <div>
      My Number: <span class="number"><%= @player.number %></span>
    </div>
  </div>
  <div id="right">
    <%= link_to "LEAVE", edit_player_path(@player) %>
  </div>
</div>

<div id="main">
  <div>
    If you leave now, you must selected one of these fates to suffer and one of these changes to achieve. If you do not wish too, <%= link_to "you must remain inside.", player_path(@player)%>
  </div>
  <br>
  <%= form_for @player do |f| %>
    <%= f.hidden_field :left, value: true %>
    <% @outcomes[:fate].each_with_index do |fate, index| %>
      <div class="edit-line">
        <%= f.radio_button :fate, fate, checked: index == 0 %><%= f.label :fate, fate, value: fate %>
      </div>
    <% end %>
    <br>
    <% @outcomes[:change].each_with_index do |change, index| %>
      <div class="edit-line">
        <%= f.radio_button :change, change, checked: index == 0 %><%= f.label :change, change, value: change %>
      </div>
    <% end %>
    <%= f.submit "Leave" %>
  <% end %>
</div>

app/views/players/index.html.erb
<div id="login">
  <div>
    Select a number to join the game.
  </div>
  <br>
  <% @games.each do |game| %>
    <div>
      Game #<%= game.code %> <%= game.created_at.strftime("%m/%d/%y") %>
      <ul>
        <% game.players.each do |player| %>
          <li>
            <%= link_to player.number, players_login_path(id: player), method: :post%>
            <% if player.host? %> (HOST)<% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/players/login_page.html.erb
<div id="login">
  <% if @games.length == 0 %>
    There are no active games right now.
  <% else %>
    <div>
      Select your number to rejoin the game. Please don't cheat!
    </div>
    <br>
    <% @games.each do |game| %>
      <div>
        Game #<%= game.code %> (<%= game.start_time.nil? ? game.created_at.strftime("%-m/%-d/%y") : game.start_time.strftime("%-m/%-d/%y") %>)
        <ul>
          <% game.players.where.not(role: :hrn).each do |player| %>
            <li><%= link_to player.number, players_login_path(id: player), method: :post%></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    If you don't see your number, the game you were a part of may have ended. If you can't remember your number, please contact your host.
  <% end %>
</div>

app/views/players/show.html.erb
<% content_for :page_classes, "in-game" %>

<div id="player-banner">
  <div id="left">
    <div id="nav"></div>
    <div>
      My Number: <span class="number"><%= @player.number %></span>
    </div>
  </div>
  
  <% if !@player.left %>
    <div id="right">
      <%= link_to "LEAVE", edit_player_path(@player) %>
    </div>
  <% end %>
</div>

<% if !@player.left %>
  <div id="game-state">
    <% if @player.game.state == "before" %>
      <h3>Connecting<span class="one">.</span><span class="two">.</span><span class="three">.</span></h3>
      The game will begin shortly.
    <% end %>
  </div>
  <%= render partial: "conversation_list", locals: {player: @player, conversations: @player.conversations, use_from: false} %>

  <script>
    playerPage(<%= @player.id %>);
  </script>
<% else %>
  <div id="game-state">
    <h3>DISCONNECTED</h3>
    <div>You may come out now</div>
  </div>
  <div id="main">
    <h3>FATE: <%= @player.fate %></h3>
    <h3>CHANGE: <%= @player.change %></h3>
  </div>
  <div class = "centered small">
    <%= link_to "Return to Front Page", root_path %>
  </div>
<% end %>